service: tabelog-scraping
frameworkVersion: "2"

provider:
  name: aws
  runtime: python3.8
  region: ap-northeast-1
  lambdaHashingVersion: 20201221

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - s3:*
          Resource: "arn:aws:s3:::tabelog-scraping-input/*"

functions:
  hello:
    handler: handler.hello
    events:
      - s3:
          bucket: "tabelog-scraping-input"
          event: s3:ObjectCreated:*
          existing: true

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: "tabelog-scraping-input"
